name: JS Code Linting

on:
    push:
        branches:
            - main
            - 'release/**'
        # Only run if JS/JSON/Lint/NVM files changed.
        paths:
            - '.github/workflows/js-lint.yml'
            - '**.js'
            - '**.json'
            - '.eslint*'
            - '.nvmrc'
            - '.prettierignore'
            - '.wp-env.json'
            - '**/package.json'
            - 'package-lock.json'
    pull_request:
        branches:
            - main
            - 'feature/**'
            - 'release/**'
        # Only run if JS/JSON/Lint/NVM files changed.
        paths:
            - '.github/workflows/js-lint.yml'
            - '**.js'
            - '**.json'
            - '.eslint*'
            - '.nvmrc'
            - '.prettierignore'
            - '.wp-env.json'
            - '**/package.json'
            - 'package-lock.json'
        types:
            - opened
            - reopened
            - synchronize

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
    js-lint:
        name: JS Lint
        runs-on: ubuntu-latest
        permissions:
            actions: write
            contents: read
        timeout-minutes: 20
        steps:
            - uses: styfle/cancel-workflow-action@0.12.1

            - uses: actions/checkout@v4

            - name: Setup Node.js (via .nvmrc)
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: npm install
              run: npm ci

            - name: JS Lint
              run: npm run lint-js
